### ISSUE TITLE
issues with ha 0.101

### ISSUE THREAD

**Issue by ThomasADavis** [magico13/ha-emporia-vue#1]
```
2020-05-20 12:33:04 WARNING (MainThread) [homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for emporia_vue doing I/O at custom_components/emporia_vue/sensor.py, line 15: vue_devices = vue.get_devices()
```

```
2020-05-20 12:33:18 WARNING (MainThread) [homeassistant.helpers.translation] emporia_vue: the '.translations' directory has been moved, the new name is 'translations', starting with Home Assistant 0.111 your translations will no longer load if you do not move/rename this 
```

also, I have two emporia's, one with the 8 port expansion, and the other gets data from the PGE smart meter.   Is there a way to see all values?

**Comment by magico13** [comment]
I'm on an older build of Home Assistant still. There aren't any translations at the moment so the translations should be fine. The issue with the event loop isn't surprising, there's a lot more io going on in general than I would like. So far this plugin is just really hastily thrown together to run on my HA system.

I only have the one Vue and don't have the expansion but I tried to write this in a way where it should create a separate sensor for each "channel" on each "device" under your account. For instance I have a single "sensor.power_7466_123" for the main device. You should hopefully have several sensors listed under the integration configuration.

**Comment by ThomasADavis** [comment]
I found that the two main power values are there, but don't see the other 8 sensors..
![Screenshot_2020-05-20_13-37-37](https://user-images.githubusercontent.com/12158973/82494868-1c177b80-9a9f-11ea-805c-b43df1f8064c.png)

What's silly is that number does not correlate to anything I can find the app..  and I don't see anything from the expansion unit.

**Comment by magico13** [comment]
I'll have to figure out why the other channels aren't showing up. The 123 are the three channels built into the main unit (only two are normally used, the third is if you have 3 phase power) and should correspond to the "Main" in the app for the last minute (app lists in kilowatts, api gives it in watts).
![image](https://user-images.githubusercontent.com/5289685/82495760-994fea00-9ab9-11ea-8a08-0995628cbc18.png)

**Comment by ThomasADavis** [comment]
yes, but when you have more than one, which one is which?  It appears that the lower number (ie, 10854) was the 1st installed, and the higher number was the second one installed.  but in the app, I cannot find which meter the 10854 corresponds to.

**Comment by magico13** [comment]
Oh yeah, I could see how that's a problem. I should be able to update the display name to something more useful so you can tell them apart.

**Comment by magico13** [comment]
I updated to fix the translation folder issue and to use the device name in the display name which should help you figure out which is which. Not sure yet about the other sensors and I created #2 to address the IO in the event loop.

**Comment by ThomasADavis** [comment]
Just updated, and got this error:

```
2020-05-20 22:28:43 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up emporia_vue platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 178, in _async_setup_platform
    await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
    return fut.result()
  File "/config/custom_components/emporia_vue/sensor.py", line 20, in async_setup_entry
    device = vue.populate_device_properties(device)
  File "/usr/local/lib/python3.7/site-packages/pyemvue/pyemvue.py", line 53, in populate_device_properties
    device.populate_location_properties_from_json(j)
  File "/usr/local/lib/python3.7/site-packages/pyemvue/device.py", line 47, in populate_location_properties_from_json
    if 'airConditioning' in li: self.air_conditioning = li['airConditioning']
TypeError: argument of type 'NoneType' is not iterable
```

**Comment by magico13** [comment]
I made a change in the base library that will hopefully fix that issue and then updated this to use the new version. Try it out and let me know if it gives you any issues.

**Comment by ThomasADavis** [comment]
The update is working!  and I can now see which meter is which.

**Comment by magico13** [comment]
Are you still having any issues? If not I will close this. If you're still not seeing the expansion module channels then I'll open a separate issue for tracking that since other people will probably want to watch that. I opened #2 previously to track the warning about IO in the event loop. No real rush to reply, just trying to do a bit of cleanup.

**Comment by ThomasADavis** [comment]
still not seeing the expansion module, otherwise it's working.  You can add this:  https://emporiaenergy.com/how-the-vue-utility-connect-works/ as working, assuming it's supported by your power company (PGE here, and it works)

I need to pull down the library and see what is going on for the expansion module.
