### ISSUE TITLE
can not install with latest HA

### ISSUE THREAD

**Issue by DiscusZ** [magico13/ha-emporia-vue#104]
when using the latest HA when I try to add this repo  I get "Invalid Add-on repository!"    I am using the exact link as per the github page

**Comment by magico13** [comment]
You might be trying to install it as an "addon" rather than a custom component through HACS. That's not supported, nor will it be, you either have to install manually or through HACS.

**Comment by DiscusZ** [comment]
That is the problem maybe I do now know what HACS is or how to install,   Finally figured this out.   HA docs about HACS are so hard to find.  

Thanks

**Comment by fusionstream** [comment]
Time to close this perhaps

**Comment by DiscusZ** [comment]
Yes we can close this issue
