### ISSUE TITLE
Emporia plugs just stopped being available

### ISSUE THREAD

**Issue by wbarber69** [magico13/ha-emporia-vue#107]
My emporia plugs, everyone of them have stopped working in HA.  They all show status unavailable.  They were all working 2 hours ago.  Restarted, reloaded.  Nothing seems to bring them back online.  I can see and control them perfectly fine through the emporia app.  But HA can no longer see them.

**Comment by jscherry** [comment]
Same problem with plugs not working. It started after updating to the new home assistant beta 2022.3.1b

**Comment by magico13** [comment]
Seeing the same thing here without changing anything, investigating now.

**Comment by magico13** [comment]
Some URLs appear to have changed. I'll get those updated in PyEmVue and then will push out a new release.

**Comment by wbarber69** [comment]
Cool.  I have been thinking about replacing all my emporia stuff with a more local option but I’m not quite ready yet! Lol

**Comment by magico13** [comment]
> Cool. I have been thinking about replacing all my emporia stuff with a more local option but I’m not quite ready yet! Lol

You might not need new hardware for that! There are some ways to swap the firmware with a local one, see this tutorial for instance for swapping the Vue firmware with ESPHome: https://gist.github.com/flaviut/93a1212c7b165c7674693a45ad52c512. I've also seen people mention Tasmota (I think, or a similar project) working on the plugs.

**Comment by magico13** [comment]
This should be fixed now with v0.7.3. Only change is an update to PyEmVue to fix the API call to get outlet info.
