### ISSUE TITLE
Meter read date in app?

### ISSUE THREAD

**Issue by jscherry** [magico13/ha-emporia-vue#116]
Does the date set in the app for the first of the billing month transfer over to HA? I've not found a way in HA energy to change the first day of the month? Wanted this to compare my consumption and bill to the readings in HA energy. Thanks

**Comment by magico13** [comment]
Yes and no. The Monthly sensor that the integration pulls in is tied to the setting in the app, but I don't think you can change the start date in the energy dashboard yet.

**Comment by jscherry** [comment]
thanks
