### ISSUE TITLE
Is there a way that I can integrate 2 Emporia accounts?

### ISSUE THREAD

**Issue by ripvega** [magico13/ha-emporia-vue#124]
As per the title. I need more than 16 monitors so thought I'd buy another 1 or 2 devices.

**Comment by magico13** [comment]
You can have multiple under one account, though I've typically seen that as one being nested under another such as for a sub panel. You may be able to have two in the same panel, with one set up to monitor the mains + 16 and another with the individual channels nested under the first and the mains clamps disconnected.

**Comment by ripvega** [comment]
Thank you.
