### ISSUE TITLE
This integration does not support configuration via the UI

### ISSUE THREAD

**Issue by Wheresitat** [magico13/ha-emporia-vue#153]
Hello,

I'm running HA through docker. I recently got the Emporia Vue and attempted to integrate it into my HA.
I get the following error:

This integration does not support configuration via the UI. If you followed this link from the Home Assistant website, make sure you run the latest version of Home Assistant.

Version of HA i am running is :
Home Assistant 2022.8.6
Frontend 20220802.0 - latest

Any ideas on resolving this one?

Thanks

**Comment by magico13** [comment]
That's odd, it only supports configuration through the UI. You're a few months behind on Home Assistant versions but not far enough that it should make a difference.

Make sure you're installing it via HACS, which itself requires adding files to your configuration directory. I also run through docker and have a volume mounted to a folder on the host to make that simpler.

**Comment by Wheresitat** [comment]
Thanks for the response.
I have installed through HACS. https://prnt.sc/C8QOkuYuhWH1
Then, go to Settings -> Integrations -> http://prntscr.com/fJZqbSNAiYo8
and finally i get this https://prnt.sc/BjenF-BGvEFs

I guess i can try updating HA to the latest but failing that any other ideas? Am i doing anything else wrong?

**Comment by magico13** [comment]
That all looks correct to me. I'll try to see if there's something I'm missing in the manifest or something. Maybe try fully removing it from HACS and adding again, maybe it didn't install properly.

**Comment by Wheresitat** [comment]
Ok will try that too and let you know how it goes, thanks again for your help.

**Comment by Wheresitat** [comment]
Updating to the latest version allowed me to enter my Emporia credentials and add the entities. Will continue to test.

Thanks again
