### ISSUE TITLE
Huge amount of energy returned on a specific day

### ISSUE THREAD

**Issue by jfroy** [magico13/ha-emporia-vue#156]
I recently noticed my November energy states showed a huge amount of energy returned to the grid, which is impossible (I don't have any solar or other production method). Looking at the energy dashboard, there was a huge amount of energy returned on a specific day. I have no idea what caused it. Other days look fine.

![emporia-returned-energy](https://user-images.githubusercontent.com/49554/201755293-12643b46-2d0d-4221-b729-bf5e761aa49d.jpg)

**Comment by jfroy** [comment]
I am using the "1,2,3 1D" sensor. The billing day is set to the 1st of the month.

![emporia-10-12](https://user-images.githubusercontent.com/49554/201759589-e08027f8-ed62-4f27-a173-55a9ba496ea2.jpg)

**Comment by jfroy** [comment]
I think I maybe know what happened. I did a bunch of maintenance work in HA around that date and I definitely did a full purge of my recorder database:

```yaml
service: recorder.purge
data:
  keep_days: 0
  repack: true
```

I am guessing that's what screw it up.

**Comment by magico13** [comment]
That definitely sounds like it could affect the stats. I don't see anything out of the ordinary with that graph, so I would probably just try to fix the statistics manually and keep an eye on it if you do a purge like that again.

**Comment by jfroy** [comment]
Nuked the bad stats. Thanks for the help.
