### ISSUE TITLE
Is data read directly from hardware or via Emporia cloud service?

### ISSUE THREAD

**Issue by nickdos** [magico13/ha-emporia-vue#16]
I'm just researching energy monitoring hardware and looking at this integration, I'm unable to determine if it reads the data directly from the hardware module or if the data is read from a hosted service that is external.

I'm not keen to rely on a hosted service due to the risk of it being pulled, so looking for a "no cloud needed" solution.

**Comment by magico13** [comment]
Unfortunately it is read from their cloud api, not directly from the hardware.
