### ISSUE TITLE
Question: Renaming entity id consequences?

### ISSUE THREAD

**Issue by hJdTzv7G** [magico13/ha-emporia-vue#169]
Hi, I notice in the readme that "The Entity ID for each sensor ... cannot be changed. " but I changed the entity id and it still seems to be working even after a restart of home assistant.

Just wondering what the context is behind the sentence in the readme saying it cannot be changed?

**Comment by magico13** [comment]
There's an internal entity id set by the integration that physically cannot be changed, except maybe by manipulating the database, which is the "real" one used by Home Assistant. That id is how you can remove and re-add the integration without losing historical data. The entity id that you see in Home Assistant's UI is closer to a name, you can still mess up some things by changing it but not permanently.

**Comment by magico13** [comment]
Specifically I'm talking about the unique I'd as documented here: https://www.home-assistant.io/faq/unique_id/

That documentation could probably do with an update, which all of the documentation could probably use.
