### ISSUE TITLE
SmartThings?

### ISSUE THREAD

**Issue by josephny** [magico13/ha-emporia-vue#17]
I am so excited to have found your Python library and this implementation.

Unfortunately, I don't use Home Assistant (didn't even know it existed before finding this).

Any chance you have SmartThings code available (DTH/App)?

I'm not a programmer so it's not an option for me make it (without losing whatever sanity might be left).

Thanks!

**Comment by magico13** [comment]
Unfortunately I have no experience with SmartThings so I don't have anything at the moment. It's always possible someone else decides takes that up but unfortunately I probably won't be able to, sorry.

**Comment by josephny** [comment]
Understood -- thank you.
