### ISSUE TITLE
HA integration?

### ISSUE THREAD

**Issue by xcentric7881** [magico13/ha-emporia-vue#170]
Integrated this, including getting the 'master' version - only shows 3 entities - minutes, hours, days - can't see individual channels.  Is this a user error, or a bug?

Note too that all 3 entities show 0.....

**Comment by magico13** [comment]
It should have a separate device for each channel you see in the app. If you're not seeing that, try to reload the integration so it fetches the device tree again. If that still doesn't work then check in the logs to see if there's anything reported for the emporia_vue integration.

**Comment by xcentric7881** [comment]
thanks for quick response.  It was actually a different issue - Emporia had disconnected, so there was noting to report..... Refixed the connection, and now entities showing.
