### ISSUE TITLE
Cannot connect

### ISSUE THREAD

**Issue by JP13090** [magico13/ha-emporia-vue#173]
I lost the ability to control Emporia switches today. I can still see the energy management side, but I am unable to have any automations turn on or off the switch. I am able to control the switch from within the Emporia app, but not within home assistant. I don't remember the message but it did provide a URL that apparently was bad. I did not get a screenshot of it.

Thinking it was a bad URL or account, I logged into Emporia via the app and changed my password. Then, I came back to home assistant and deleted the integration and reloaded it. With the new password, I would have to provide that of course. When I entered my email address and password, "unexpected error" posted.

The switches do everything they are supposed to do from within the Emporia app. From home assistant, the only thing working currently is the power meter.

**Comment by magico13** [comment]
I pushed a release earlier today around 2:35PM EST, version 0.8.1, that fixes this. Unfortunately all you needed to do was update to that version and reboot. Some common issues I've seen with logging in is that you should make sure you enter your email address all lowercase and also the password is case-sensitive. If you still get an error when logging in you can try to get the full error message from the logs `{yourHAInstance}:8123/config/logs`.

**Comment by JP13090** [comment]
Yeah, I should have checked HACS for any updates before I opened that.  But when I logged out of the emporia app, I couldn't remember my password, so changing that, I had to use that new PW in the HACS integration too.  Thanks for the quick response.  Updated to 0.8.1. Sorry for the bother.  So much of my automations depend on your great work.  Thank you.
