### ISSUE TITLE
add support for emporia Vue Plugs

### ISSUE THREAD

**Issue by haddood** [magico13/ha-emporia-vue#18]
I just got 4 of emporia plugs (https://www.amazon.ca/Emporia-Energy-Monitoring-Certified-Package/dp/B08CVSSVWP/ref=sr_1_4?dchild=1&keywords=emporia&qid=1604943637&sr=8-4), to increase my consumption monitoring. they are already detected as meters for emporia vue integration. it will be great if they are detected as switches too.

**Comment by magico13** [comment]
It's on my list, I've got one of them too specifically for this purpose. There's already #14 for this though so I'm going to close this as a duplicate.
