### ISSUE TITLE
can we have charge adjusting charge rate for EV charger?

### ISSUE THREAD

**Issue by zebel212** [magico13/ha-emporia-vue#182]

**Comment by magico13** [comment]
You can already change the amps for the charger/EVSE by calling the `emporia_vue.set_charger_current` service with either the device id for the charger or the entity id. You can pretty easily test it out from the Services tab under the Home Assistant Developer Tools.

**Comment by zebel212** [comment]
thank you sooo much!
you are awesome!!

**Comment by zebel212** [comment]
only issue is when I set the current it will turn off the charging mode and I have to change it back on, is there a way to change the charging rate and keep the charging mode ON?
thanks

**Comment by magico13** [comment]
Someone else reported that once and it was because they weren't on the latest version. Calling the service shouldn't alter anything but the charging current.

**Comment by zebel212** [comment]
I'm running v0.8.1

**Comment by zebel212** [comment]
it is working fine now , thanks
