### ISSUE TITLE
Unable to Login

### ISSUE THREAD

**Issue by maxrhodes5** [magico13/ha-emporia-vue#192]
Hello, I've been using this integration for about a month and have had only minor issues with the 1min sensors.  So I thought it would be a good idea to remove the integration and set it back up without selecting the 1min sensor option when adding the integration.  However now I'm unable to login and just get an unexpected error.  I'm in the process of moving over to HAOS from docker so I have a second instance I'm setting up from scratch and I'm still having the same issue.  I have validated my credentials are correct.  Thanks.

**Comment by magico13** [comment]
This is typically a problem with capitalization. Make sure your email address is all lowercase and that it's not putting a capital letter for the first character. That's something I need to add in next time I'm working on this.

**Comment by maxrhodes5** [comment]
Thanks for the quick follow up!  I've verified I'm putting the email address in the correct format and have also copied and pasted the same on their website to validate it's correct.  

If I don't select the 1min option will that disable the queries to their server or does it just disable the entities in home assistant?  I noticed that past week or two Home Assistant is very slow to start with this integration.  Since I don't really need this data I was hoping by not selecting the 1min option it would speed up the startup and also stop requiring me to restart home assistant daily to get the 1min values back. 

I'm hoping to get daily usage to go along with my rtl-sdr data I'm getting for my gas and water meters.  Unfortunately I have a newer smart meter for my electricity that is encrypted.  Your integration help solve that issue.  Thanks again for the help and awesome integration!

**Comment by maxrhodes5** [comment]
I got my HA Core Docker (original install) to work again.  But the HAOS which I plan to move to soon had the same error.  This time I got the logs to include.  Also it's adding the integration to the page but said it failed to set up.  The other instance did the same until a few minutes ago when it finally came up to assign the areas.  My guess is it's an issue on their end and it's just timing out in the integration.  It's been very slow lately as mentioned before to start home assistant due to this integration.   Not sure if this will help or not and let me know if I should close the issue.  Thanks!

2023-04-08 16:17:02.857 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration emporia_vue which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-04-08 16:32:24.851 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Customer 32*** for emporia_vue
File "/config/custom_components/emporia_vue/__init__.py", line 94, in async_setup_entry
2023-04-08 16:47:36.867 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Customer 32*** for emporia_vue
File "/config/custom_components/emporia_vue/__init__.py", line 94, in async_setup_entry
2023-04-08 18:09:33.990 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Customer 32*** for emporia_vue
File "/config/custom_components/emporia_vue/__init__.py", line 94, in async_setup_entry

![still starting](https://user-images.githubusercontent.com/125677438/230744723-977f2425-2d8c-4449-b894-9ec3212d99ed.jpg)

**Comment by maxrhodes5** [comment]
Back to normal today... maybe Emporia had maintenance last night that fixed the issue.  I was able to add the integration very quickly to my HAOS build just a few mins ago.  Thanks again for your help!
