### ISSUE TITLE
Midnight happened recently for id 130639-1,2,3-1D! Timestamp is 2023-04-26 00:00:01-04:00, midnight is 2023-04-26 00:00:00-04:00, previous reset was 2023-04-25 00:00:00-04:00

### ISSUE THREAD

**Issue by tanbronson** [magico13/ha-emporia-vue#195]
I've been getting error messages in my log, and wanted to know if this was an actual error...
Thanks for providing this to the community

 `Logger: custom_components.emporia_vue
Source: custom_components/emporia_vue/__init__.py:167
Integration: Emporia Vue ([documentation](https://github.com/magico13/ha-emporia-vue), [issues](https://github.com/magico13/ha-emporia-vue/issues))
First occurred: April 25, 2023 at 12:01:49 AM (2 occurrences)
Last logged: 12:00:49 AM

Midnight happened recently for id 130639-1,2,3-1D! Timestamp is 2023-04-25 00:00:54-04:00, midnight is 2023-04-25 00:00:00-04:00, previous reset was 2023-04-24 00:00:00-04:00
Midnight happened recently for id 130639-1,2,3-1D! Timestamp is 2023-04-26 00:00:01-04:00, midnight is 2023-04-26 00:00:00-04:00, previous reset was 2023-04-25 00:00:00-04:00`

**Comment by magico13** [comment]
It's not actually an error, just some debug logging that I forgot to take out while trying to deal with the data issues/spikes that seem to happen between midnight and 1 AM.

**Comment by tanbronson** [comment]
If it's not an error, then there's no reason to keep this open.

thanks
