### ISSUE TITLE
Maintogrid 1D doesn't work

### ISSUE THREAD

**Issue by DarkStar1973** [magico13/ha-emporia-vue#197]
First thanks for this integration !!
I have a solar production. All is ok in emporia webapp, but in HA the value of "maintogrid" is false.

Actual my solar produce more than my house use:

![Capture d’écran du 2023-04-27 11-21-53](https://user-images.githubusercontent.com/19590516/234820117-16aa5c4d-85df-416d-8469-d1b7ba78eae8.png)

The sensor for my solar production (channel 16 on emporia) is correct and show the production

![Capture d’écran du 2023-04-27 11-15-04](https://user-images.githubusercontent.com/19590516/234820425-946f941f-b82d-4681-9fb9-8bb4d3d9b543.png)

The "MainsFromGrid" is ok too:

![Capture d’écran du 2023-04-27 11-23-04](https://user-images.githubusercontent.com/19590516/234820603-1bdc4d40-d393-4112-8a34-5ffa74093d18.png)

Here we can see that i inject to the grid because the value is actually negative for the main phase sensor:

![Capture d’écran du 2023-04-27 11-31-30](https://user-images.githubusercontent.com/19590516/234821739-b968aebb-6468-4ded-b684-c397d86db00c.png)

But result are false on "Mainstogrid":

![Capture d’écran du 2023-04-27 11-32-23](https://user-images.githubusercontent.com/19590516/234821998-4f38b6b1-07ef-41b8-8911-8a76260a9411.png)

**Comment by DarkStar1973** [comment]
Other graphs, "Mainstogrid" stay null on energy dashboard:

![Capture d’écran du 2023-04-27 11-46-46](https://user-images.githubusercontent.com/19590516/234826040-af7f1431-1a17-48b4-b993-3a687b62c5d8.png)

![Capture d’écran du 2023-04-27 11-46-29](https://user-images.githubusercontent.com/19590516/234826132-56dae3fc-e802-4209-a103-f2743e474004.png)

**Comment by magico13** [comment]
Odd. I don't have solar so I can't easily check what the app reports for those channels. You should be able to compare in the app by swapping to the "Day" option at the bottom. If the data is bad in the app too when looking at the overall page there's not much I can do. If you look at the graph in the Emporia app that pulls from a different data set, the instant data on the main page is primarily what Home Assistant uses.

**Comment by DarkStar1973** [comment]
IT work now, i think i had not enough data, was just installed. I close.
