### ISSUE TITLE
Only 10-14 rolling days are kept on HomeAssistant, can't look at historic data

### ISSUE THREAD

**Issue by dmontoya3** [magico13/ha-emporia-vue#205]
I have about a month with the Emporia Vue system and noticed that the integration doesn't query data older than two weeks. I've installed it on the last week of April and as days go by, on Home Assistant I "lose" sight of historical data. Data is still on the Emporia Vue website so the information is not being deleted. 

![image](https://github.com/magico13/ha-emporia-vue/assets/41489098/34735f61-860e-4674-91ef-0b0e64becd27)

Is there a way to query older data or store it on a database like the grafana integration?

![image](https://github.com/magico13/ha-emporia-vue/assets/41489098/e1a57fce-7f14-45b2-bc66-a9aa621767de)

**Comment by magico13** [comment]
The integration only requests the most recent data each update, keeping that data is dependent on your settings in Home Assistant. The long term statistics used for the Energy Dashboard are kept forever afaik. The individual sensor measurements are kept for whatever your recorder options are set to, which I believe defaults to 10 days. You can either change that, use the long term statistics for your graphs, or also export the data somewhere else.

https://www.home-assistant.io/integrations/recorder/
https://data.home-assistant.io/docs/statistics/
