### ISSUE TITLE
Cannot get the charger to show any control interfaces.

### ISSUE THREAD

**Issue by shayes83** [magico13/ha-emporia-vue#208]
This is a great integration!   I love these devices, however today I added the charger unit and I am having a hard time getting the control GUI to appear.  I dont know if there is documentation I am missing or what.  I can see the devices, Outlet sensor, and two additional sensors.  which one should show the control interfaces???  I am sure I am missing something completely simple here!  Thanks again for a great interface.

**Comment by magico13** [comment]
The way the EVSE is implemented the "switch" will control whether the charger is paused or active. It also has attributes on it for some of the additional info that you see in the Emporia app. If you want to change the charging current you can use a service call to do so, but there's not a slider or anything on the device page for that (yet).

**Comment by shayes83** [comment]
Yes, I saw something on a recent closed post and was able to get it going just fine!  Nice work on this!

**Comment by shayes83** [comment]
So now I am getting an error that says incorrect type...  I am using the following code to call the service:

service: emporia_vue.set_charger_current
device_id: switch.tesla_car_charger
data:
  charging_rate: "30"

admittedly I am not that familiar with call service

**Comment by magico13** [comment]
I believe the data should look like `current: 30`. No quotes and I believe the property is called `current`

**Comment by magico13** [comment]
Hmm. I'm not too sure on that one. I'm not at a point where I can get you a good example to work with, I'll try to get you one by tomorrow. I have this one from one of my automations that might help but might not have enough context.


```
- service: emporia_vue.set_charger_current
        data:
          current: 25
        target:
          device_id: c162253d9a697c72832eb86955af29cc
```

**Comment by shayes83** [comment]
Yeah, something is conflicting, these service calls should be simple.  It looks like the logs are indicating there may be a python issue.  Would me running py 3.11 have anything to do with this?  I seem to be getting a 400 error when calling the api??

Latest Log

Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/emporia_vue/__init__.py:267
Integration: Home Assistant WebSocket API ([documentation](https://www.home-assistant.io/integrations/websocket_api), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+websocket_api%22))
First occurred: 9:14:16 AM (4 occurrences)
Last logged: 11:36:03 AM

[281472388967440] Error handling message: Unknown error (unknown_error) Sean T Hayes from 192.168.0.184 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36 Edg/113.0.1774.57)
[281472700679056] Error handling message: Unknown error (unknown_error) Sean T Hayes from 192.168.0.184 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36 Edg/113.0.1774.57)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 26, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 678, in handle_execute_script
    await script_obj.async_run(msg.get("variables"), context=context)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1533, in async_run
    await asyncio.shield(run.async_run())
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 410, in async_run
    await self._async_step(log_exceptions=False)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 454, in _async_step
    self._handle_exception(
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 477, in _handle_exception
    raise exception
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 452, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 685, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1910, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1950, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/config/custom_components/emporia_vue/__init__.py", line 267, in handle_set_charger_current
    updated_charger = await loop.run_in_executor(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pyemvue/pyemvue.py", line 161, in update_charger
    response.raise_for_status()
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.emporiaenergy.com/devices/evcharger

**Comment by shayes83** [comment]
so when I attempt to follow the address listed above:

https://api.emporiaenergy.com/devices/evcharger

I get this message: 

{
    "message": "Missing Authentication Token"
}

something is not connecting to the API somehow.

**Comment by magico13** [comment]
Download the latest update, v0.8.2, which fixes the services.yaml and should make this a bit easier. Once you do so and restart Home Assistant, you should be able to see the `Emporia Vue: Set Charger Current` service in the Developer Tools (see attached pic)  then you can select your charger and use the slider, and verify that the call succeeds. The nice thing about that UI is that it'll limit the device list to just chargers.

From there you should be able to swap to the yaml view to get something you can use in an automation. I think the issue you're running into might be because you have an entity id in a field for a device id. Device ids are big random hexadecimal numbers, entity ids are the nicely named things.

Example with entity id:
```yaml
service: emporia_vue.set_charger_current
data:
  current: 30
target:
  entity_id: switch.ev
```

Example with device id:
```yaml
service: emporia_vue.set_charger_current
data:
  current: 30
target:
  device_id: c162253d9a697c72832eb86955af29cc
```

**Comment by shayes83** [comment]
Hmm, I will sure try to give it a go.  I am running HA on an ODRIOD N2+ so I may have to dig around as to how I install this on the ODRIOD running the HA OS...  Im sure there is a way.

**Comment by shayes83** [comment]
OK, seems to be the same issue ran from a Ubuntu server that I run Frigate and Deepstack on.... here is the print out:


Enter your email: XXX
Enter your password: XXXX
Charger data:
[
    {
        "device_gid": 234967,
        "charger_on": false,
        "message": "Off",
        "status": "Standby",
        "icon": "CarNotConnected",
        "icon_label": "Paused",
        "icon_detail_text": "Charger is not connected to a vehicle.",
        "fault_text": null,
        "charging_rate": 20,
        "max_charging_rate": 40,
        "off_peak_schedules_enabled": false,
        "custom_schedules": [],
        "load_gid": 134154
    }
]
Press enter to turn off the charger and print the charger data again...
Traceback (most recent call last):
  File "/home/seanthayes/Documents/pyemvuetesting/EMVUETEST.py", line 33, in <module>
    vue.update_charger(charger, on=False)
  File "/usr/local/lib/python3.10/dist-packages/pyemvue/pyemvue.py", line 172, in update_charger
    response.raise_for_status()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.emporiaenergy.com/devices/evcharger

**Comment by shayes83** [comment]
Sounds great!  just let me know.  

Grasping at straws here, but could there be a traffic conflict, like a port the script is using or something to that effect?

**Comment by magico13** [comment]
It's all pretty standard HTTPS traffic and since the GET calls are working it seems like it's just something with the PUT to update the charger. Not sure what's different about your situation though, it could be related to an app update, a newer hardware or firmware version, or just a bug in my code.

**Comment by magico13** [comment]
I think I've figured it out. At some point recently they started requiring a PIN. Mine was set up long enough ago that it had no PIN so it didn't require it on the request. When I set one in the app I got a 400 response when I didn't explicitly include it in the request. Looks like I should be able to fix this with a PyEmVue update.

**Comment by shayes83** [comment]
Mike you have been more than helpful and I owe you a coffee!!!  I will be happy to try anything you need me to, just let me know!

**Comment by magico13** [comment]
Try updating to 0.8.3 and see if that works. If somehow that's not the problem, though I'm pretty sure the PIN is the problem since it had the same error, then at least that version will print out a bit more to the log.

**Comment by shayes83** [comment]
Actually, the service call is now stopping the charger when attempting to change the charging current.  I have to restart the charge.

**Comment by magico13** [comment]
There's an issue #193 for that happening. That one I'm even less sure about so I can't promise as quick of a fix for that, if you're calling the service from an automation you may want to also have a step to turn the switch on. Are you ok with closing this one out and moving discussion over to that issue?

**Comment by shayes83** [comment]
Absolutely.  Thanks for your help! I will keep an eye on 193
