### ISSUE TITLE
Restore Deleted Entity

### ISSUE THREAD

**Issue by klkohl** [magico13/ha-emporia-vue#209]
One entity was showing as unavailable. Before I did enough research I deleted that entity and now I can't see how to add/restore the entity. I tried deleting the integration and reinstalling, but the missing entity didn't come back. How can I add/restore the missing entity?

**Comment by magico13** [comment]
It should be that upon a server restart or just reloading the integration then it should be added back. If the API still isn't giving data for it, it won't show up, so you'll need to get to the root of why that particular one isn't working. Does it have valid data in the Emporia app? Or is it just 0 there? 

If it's got non-zero data in the home page of the app with the timing set to 1 minute, then try to reload the integration and it should get detected. If it's not working properly in the app then the CT might need to be unplugged and plugged back into the main unit, loose connections can cause them to stop reporting data. If it's an outlet or EV charger it could be a network issue or a failure in the device.

**Comment by klkohl** [comment]
Thanks. It's working now.
