### ISSUE TITLE
Integration Fails Initialization 

### ISSUE THREAD

**Issue by virtualbitzz** [magico13/ha-emporia-vue#214]
This integration has been failing to load for me in the last few days. I'm not seeing much in the logs other than generic initialization failure messages. 

Running Home Assistant OS in a VM, version 2023.7.3

**Comment by magico13** [comment]
Odd, could just be bad timing and it's starting up when the API is unstable. If you changed your password that could also do it. If you keep seeing issues, check the app at the same time and if the data in the app (especially for the 1 second and 1 minute levels) is bad then that's probably why. If it doesn't resolve you can try installing the "master" version of the integration which has some changes to the initialization to build the sensors off the device tree more than the initial usage info, but it sounds like it's maybe not even getting that far.

**Comment by virtualbitzz** [comment]
I'm actually not sure sure if it's just failing to start on startup / restart of HA or if it's crashing. It seems to be working now. I'll close this and re-open if the behavior comes back.
