### ISSUE TITLE
The ability to adjust the "Monthly" to match the billing cycle from the provider

### ISSUE THREAD

**Issue by CDKrash** [magico13/ha-emporia-vue#228]
Can the ability to adjust the days of the month that are tracked be implimented? Meaning be able to select the day the month begins on istead of the 1st -30th. The power provider usually reads the meter on the 25th of the month and not the 1st. It would be great if I could match what I see in HA to what the provider shows for usage.

**Comment by magico13** [comment]
You can do that in the Emporia app, the Home Assistant integration will follow for the monthly sensor, resetting when the specified day happens. It won't affect the energy dashboard though since that's purely within the Home Assistant core's realm and not something I can change.

**Comment by magico13** [comment]
In the app it's under Household Info. You then have to set it for each device.
![Screenshot_20231015-123156.png](https://github.com/magico13/ha-emporia-vue/assets/5289685/ec93f0bb-0d18-4a53-aa62-b5b39e21a589)

**Comment by CDKrash** [comment]
I did adjust that, but was wondering if there is a way to track that in HA.

**Comment by CDKrash** [comment]
> You can do that in the Emporia app, the Home Assistant integration will follow for the monthly sensor, resetting when the specified day happens. It won't affect the energy dashboard though since that's purely within the Home Assistant core's realm and not something I can change.

Thank you sir. That's what I needed to know. Cheers and great intigration!
