### ISSUE TITLE
Changing EVSE charging current turns on charging

### ISSUE THREAD

**Issue by wirecuttr** [magico13/ha-emporia-vue#233]
If I make a service call to change the charging current, the EVSE will also start charging. (i.e., it will take it out of the paused state and start charging.)
Not sure if this was intentional, but I didn't expect it. It doesn't do that in the Emporia app. Charging rate and the start/pause are independent.

**Comment by magico13** [comment]
This is almost definitely the same problem as #193 if you're not running the master branch. With the last release it's only looking at the state when the integration started, the master branch has a fix to check the state before sending the update and should prevent it from changing.

**Comment by wirecuttr** [comment]
So you lost me a bit with the master branch stuff... I installed the integration through HACS. When I look at the integration in HACS it says v0.8.3.

My HA verion is:
Core 2023.11.0
Frontend 20231030.1

**Comment by wirecuttr** [comment]
Figured it out. Redownloaded the integration with Master version. So far looks like the issue is fixed there.

**Comment by wirecuttr** [comment]
Closing as duplicate to #193 .
