### ISSUE TITLE
Instructions say to add repo, but fails saying no repositories.

### ISSUE THREAD

**Issue by spyrule** [magico13/ha-emporia-vue#238]
So I'm trying to follow the instructions, and on HA OS 11.2, I click the 3 dots, repositories, paste the URL (https://github.com/magico13/ha-emporia-vue), and click ADD, and it fails saying no repositories found.

Anybody know what I'm doing wrong?

**Comment by magico13** [comment]
Have you installed HACS and you're adding it through that? Or are you trying to add it as an addon? It must be installed with HACS, not as an addon.

https://hacs.xyz/docs/setup/download/

**Comment by spyrule** [comment]
Yup, my bad. 🤦   Seems I forgot how to read.
