### ISSUE TITLE
When Logon 

### ISSUE THREAD

**Issue by source221** [magico13/ha-emporia-vue#25]
When login in using email and password I get an **Unexpected error!**

**Comment by magico13** [comment]
If you go into Configuration and then Logs do you see any errors related to "Emporia Vue"? Verify that you're using the correct email and password. The error handling around logging in is currently very minimal so that's something I need to work on, but it should log in correctly.

**Comment by source221** [comment]
After checking the logs in the configurations section it seems the password was incorrect. There are no more errors and it seems to work great !!
Thank you for all your hard work :)
