### ISSUE TITLE
Rounding in Sensors

### ISSUE THREAD

**Issue by DabblerIOT** [magico13/ha-emporia-vue#258]
Why are we rounding here?   Shouldn't we pass actual data back to ha?   And users of proper documents should be able to control rounding for display by using the formatting?  I do not believe rounding sensor data here is really correct or should be done.

def scale_usage(self, usage):
        """Scales the usage to the correct timescale and magnitude."""
        if self._scale == Scale.MINUTE.value:
            usage = round(60 * 1000 * usage)  # convert from kwh to w rate
        elif self._scale == Scale.SECOND.value:
            usage = round(3600 * 1000 * usage)  # convert to rate
        elif self._scale == Scale.MINUTES_15.value:
            usage = round(
                4 * 1000 * usage
            )  # this might never be used but for safety, convert to rate
        else:
            usage = round(usage, 3)
        return usage

**Comment by magico13** [comment]
Home Assistant used to not really handle data that had too much precision. More recently they added attributes to control the number of digits shown, so the rounding could probably be removed if/when those extra attributes are populated. The half a watt that the rounding might skew is potentially less than the error in the measurement by the Vue so it's not likely very significant overall.

**Comment by DabblerIOT** [comment]
How about a round (value,2) instead of a round()?   

Some well used older things don’t support it right yet.. like bar-card.

Thanks.

**Comment by DabblerIOT** [comment]
On my setup I slowed the polling down to 2 seconds, and with rounding (2), pretty much get a new value and history log every 2 seconds. :)
