### ISSUE TITLE
1D sensor resetting at 00:00 UTC leading to large negative entry

### ISSUE THREAD

**Issue by jfroy** [magico13/ha-emporia-vue#264]
I have recently installed a new Emporia Vue Smart Home Energy Monitor. It is working fine from the POV of the Emporia web and mobile apps. It showed up in the integration and seemed OK.

But every day, at 00:00 UTC (which is 17:00 PDT), the sensor resets to 0. This is unexpected and HA doesn't handle it well. It creates a large negative entry that makes it look like I returned energy.

**Comment by jfroy** [comment]
Ah, I think the new device didn't have its timezone set in the native Emporia app settings, thus defaulting to UTC. So probably not an integration problem. I've changed that and I will report back.

**Comment by DabblerIOT** [comment]
I am set the same way and am not having a problem.   At one point there was a setting in the energy configuration of if your sensor will reset to 0 periodically, not sure that setting is there anymore or not.   May want to be sure you update to the latest version of HA as in the last update improved the energy dashboard (added stacked graph for additional meters).

**Comment by magico13** [comment]
> Ah, I think the new device didn't have its timezone set in the native Emporia app settings, thus defaulting to UTC. So probably not an integration problem. I've changed that and I will report back.

That was going to be my suggestion. The Day data resets on the API-side based on the timezone set in the app. With that updated I would expect it to work correctly. If/when you add additional devices (plugs and such) make sure you set the timezone on those devices as well.

**Comment by jfroy** [comment]
> > Ah, I think the new device didn't have its timezone set in the native Emporia app settings, thus defaulting to UTC. So probably not an integration problem. I've changed that and I will report back.
> 
> 
> 
> That was going to be my suggestion. The Day data resets on the API-side based on the timezone set in the app. With that updated I would expect it to work correctly. If/when you add additional devices (plugs and such) make sure you set the timezone on those devices as well.

Is the device time zone something the integration can see? If so, it could emit a repair if the device TZ is not equal to the HA TZ.

**Comment by magico13** [comment]
> Is the device time zone something the integration can see? If so, it could emit a repair if the device TZ is not equal to the HA TZ.

Yes, it is something the integration has access to, that's an interesting idea I hadn't considered. At least I can throw a warning message into the repairs telling the user to fix it, but I might even be able to provide a fix option that will set it on the API so you don't need to use the app yourself. That's a really nice suggestion, thanks for the idea!

**Comment by jfroy** [comment]
The data reset at 00:00 PDT after configuring the device TZ.
