### ISSUE TITLE
Emporia Vue Gen 3

### ISSUE THREAD

**Issue by AngeloAna** [magico13/ha-emporia-vue#266]
Will I be able to use the brand new Gen 3 or do I have to use the older Gen 2 product?

**Comment by gmbrown21** [comment]
I just installed a Vue Gen 3 a couple of days ago and so far it appears to be working just fine in HA so far.

**Comment by AngeloAna** [comment]
That is good news. Thanks

**Comment by magico13** [comment]
I actually have a gen 3 now as well and can confirm that the standard metering functionality is working as expected.
