### ISSUE TITLE
API error

### ISSUE THREAD

**Issue by chrwei** [magico13/ha-emporia-vue#27]
I've had the integration working for at least a week, but this morning I'm getting an error.

Error fetching sensor data: Error communicating with Emporia API: 400 Client Error: Bad Request for url: https://api.emporiaenergy.com/usage/devices?start=2021-02-09T15:11:48.003545Z&end=2021-02-09T15:11:49.003545Z&scale=1MIN&unit=WATTS&customerGid=XXXX

I did install the latest updates of everything last night, but it was all working when I went to bed.

**Comment by magico13** [comment]
It looks like I'm seeing something similar locally, as of 10:11 EST my sensors seem to have stopped updating. Doing a restart of my HA server doesn't appear to have fixed it. I will have to see if they changed up the API or something but I won't be able to for a few hours.

**Comment by DarwinData** [comment]
I'm also getting:
Error fetching sensor data: Error communicating with Emporia API: 403 Client Error: Forbidden for url: https://api.emporiaenergy.com/usage/devices?start=2021-02-09T17:13:54.254461Z&end=2021-02-09T17:13:55.254461Z&scale=1MIN&unit=WATTS&customerGid=999
This just started this morning.
thanks

**Comment by chrwei** [comment]
app was updated 3 days ago on my phone, wonder if that was in preparation for a protocol change

**Comment by magico13** [comment]
The API was indeed updated and the old methods removed. I've updated PyEmVue and made a new release of this integration that should fix the issues people are seeing. Please reply or open a new issue if you have any problems. Thanks!
