### ISSUE TITLE
Authentication not working since 0.9.3 anymore?

### ISSUE THREAD

**Issue by sledge2019** [magico13/ha-emporia-vue#270]
I am still relatively new to Home-Assistant - running it in parallel with FHEM, so bear with me if I might use the wrong vocabulary.

Since January this year I was using the Emporia Vue integration, running nicely on my system without any problem. Back at that time I am pretty sure I used 0.8.3 when I started with Emporia Vue.

Sometime during Feb I upgraded to 0.9.2 or 0.9.3, and since then I cannot authenticate anylonger with Emporia Vue.

Installing the integration via HACS, I fired up the "add integration" dialog and received some error - digging into the logs the following came up:

`This error originated from a custom integration.

Logger: custom_components.emporia_vue.config_flow
Source: custom_components/emporia_vue/config_flow.py:76
integration: Emporia Vue (documentation, issues)
First occurred: 14:26:46 (1 occurrences)
Last logged: 14:26:46

Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/emporia_vue/config_flow.py", line 76, in async_step_user
    info = await validate_input(self.hass, user_input)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/emporia_vue/config_flow.py", line 47, in validate_input
    if not await hub.authenticate(data[CONF_EMAIL], data[CONF_PASSWORD]):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/emporia_vue/config_flow.py", line 37, in authenticate
    result = await loop.run_in_executor(None, self.vue.login, username, password)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pyemvue/pyemvue.py", line 355, in login
    self.auth = Auth(
                ^^^^^
  File "/usr/local/lib/python3.12/site-packages/pyemvue/auth.py", line 57, in __init__
    self.cognito.authenticate(password=password)
  File "/usr/local/lib/python3.12/site-packages/pycognito/__init__.py", line 495, in authenticate
    self._set_tokens(tokens)
  File "/usr/local/lib/python3.12/site-packages/pycognito/__init__.py", line 767, in _set_tokens
    self.verify_token(
  File "/usr/local/lib/python3.12/site-packages/pycognito/__init__.py", line 266, in verify_token
    raise TokenVerificationException(
pycognito.exceptions.TokenVerificationException: Your 'access_token' token could not be verified (The token is not yet valid (iat)).`

This behaviour remains after upgrading HASS to version 2024.4.1.

Using [PyEmVue](https://github.com/magico13/PyEmVue) directly, the authentication with emporia works like a charm, no probs at all.

Any clues / ideas on how to proceed?

Best, Tom

**Comment by magico13** [comment]
Hello, please see #260. The stack trace shows the same token validation problem meaning your clock is just out of sync enough to cause the validation to fail.

**Comment by sledge2019** [comment]
Strange. All my systems run on a strict NTP-setup, so does my system providing docker containers. Re-synced NTP for the server providing the container, no it authenticated.

Thanks for the fast solution.
