### ISSUE TITLE
Massive negative value in Energy tab

### ISSUE THREAD

**Issue by SylentButDedly** [magico13/ha-emporia-vue#274]
I'm not entirely sure if this is an integration issue or an issue with Home Assistant or maybe I'm just doing something wrong, but when I attempt to put the 1D entity into the energy tab it gives me a massive negative energy consumption. The entity itself seems to be tracking just fine

![image](https://github.com/magico13/ha-emporia-vue/assets/13735575/0a7b50ff-2993-43dc-a16a-866911fdb0c9)
![image](https://github.com/magico13/ha-emporia-vue/assets/13735575/c8054f21-75c5-463b-9b0c-cc60f14be05a)

**Comment by Esprit1st** [comment]
Actually I had that happen as well when I first activated the integration. I have solar and something was just off. It resolved itself when HA converted the data into the long term data. But you might be able to manually correct it going through the statistics tab. Hope this helps.On Apr 11, 2024 21:25, Sylent ***@***.***> wrote:
I'm not entirely sure if this is an integration issue or an issue with Home Assistant or maybe I'm just doing something wrong, but when I attempt to put the 1D entity into the energy tab it gives me a massive negative energy consumption
image.png (view on web)

**Comment by SylentButDedly** [comment]
@Esprit1st you were absolutely right! I woke up this morning and it's working perfectly fine. I did as you said and removed the outlier stats and it even retroactively fixed all of yesterdays data points. Thank you!
