### ISSUE TITLE
All sensors disappeared

### ISSUE THREAD

**Issue by DaDre** [magico13/ha-emporia-vue#28]
Since the latest HA / ha-emporia-vue updates, all my sensors disappeared. I've updated hacs to the latest, updated ha-emporia-vue to the latest from the repo (version from 2.5 hours ago), reinstalled emporia vue integration, re-logged in, still missing all sensors. Many attempts to re-install completely fresh, including full host reboots in between each step produce no results. The integration is shown with zero devices or entities. My phone emporia vue app still shows all data. Something must be missing with the new API?

**Comment by alancarrillo** [comment]
Same issue.. @magico13

**Comment by magico13** [comment]
Well that's definitely not good. Is there anything in the logs (/config/logs) for the Emporia Vue integration? What hardware do you have (first gen vs second gen Vue, expansion for 1st gen, smart plugs, etc)? Which sensors did you enable when logging in (1s, 1m, 1d, 1month, etc)?

There's still some weirdness with the new api calls I think so I can hopefully get this fixed today. It appears to be working correctly with my setup (1st gen vue + expansion, one smart plug, all sensors enabled) so I may ask you all to try some debug builds if I can't recreate the same issues.

**Comment by pleeplow20** [comment]
> 
> 
> Well that's definitely not good. Is there anything in the logs (/config/logs) for the Emporia Vue integration? What hardware do you have (first gen vs second gen Vue, expansion for 1st gen, smart plugs, etc)? Which sensors did you enable when logging in (1s, 1m, 1d, 1month, etc)?
> 
> There's still some weirdness with the new api calls I think so I can hopefully get this fixed today. It appears to be working correctly with my setup (1st gen vue + expansion, one smart plug, all sensors enabled) so I may ask you all to try some debug builds if I can't recreate the same issues.

Hey I am having the same issue the only thing I found in the logs was this and I have 2nd gen vue + expansion 

Logger: custom_components.emporia_vue.sensor
Source: helpers/update_coordinator.py:166
Integration: Emporia Vue (documentation)
First occurred: 7:09:24 AM (5 occurrences)
Last logged: 7:17:21 AM
Error fetching sensor data: Error communicating with Emporia API: argument of type 'NoneType' is not iterable

**Comment by magico13** [comment]
> File "/config/custom_components/emporia_vue/sensor.py", line 103, in async_setup_entry
CurrentVuePowerSensor(coordinator_1min, id) for idx, id in enumerate(coordinator_1min.data)
TypeError: 'NoneType' object is not iterable

Seems to imply it didn't get any data back, weird. Might be related to some of the issues people are seeing with PyEmVue so hopefully I can fix it within there and push out an update.

**Comment by pleeplow20** [comment]
> 
> 
> > File "/config/custom_components/emporia_vue/sensor.py", line 103, in async_setup_entry
> > CurrentVuePowerSensor(coordinator_1min, id) for idx, id in enumerate(coordinator_1min.data)
> > TypeError: 'NoneType' object is not iterable
> 
> Seems to imply it didn't get any data back, weird. Might be related to some of the issues people are seeing with PyEmVue so hopefully I can fix it within there and push out an update.

Ok Thank you

**Comment by FartingDaddy** [comment]
Well, It is my turn now. Everything disappeared from the integration. Only shows my client number. All the sensors are gone. I did a full re-install and updated HACS as well. Emporia tech support is saying that they did update the app as an emergency "a few days ago" and needs to be re-installed. I did so and I can see sensors working in the app, not in the Home Assistant.
@ magico13, you've made a great integration - I hope you will be able to fix it for us. Thanks for your help.

This is my LOG info:
Error while setting up emporia_vue platform for sensor
February 9, 2021, 6:56:24 PM – Sensor (ERROR) - message first occurred at February 9, 2021, 6:45:25 PM and shows up 2 times

Error fetching sensor data: Error communicating with Emporia API: 403 Client Error: Forbidden for url: https://api.emporiaenergy.com/usage/devices?start=2021-02-10T00:45:23.898866Z&end=2021-02-10T00:45:24.898866Z&scale=1MIN&unit=WATTS&customerGid=14417
February 9, 2021, 6:56:24 PM – Emporia Vue (ERROR) - message first occurred at February 9, 2021, 6:45:25 PM and shows up 2 times

**Comment by magico13** [comment]
@FartingDaddy that url is to the old API methods so make sure you're updated to the 0.3.0 version, if so there might be some other messages logged. Emporia won't provide any support for this since we're not using a public API so they're free to change it up underneath us (what happened in this case)

**Comment by pleeplow20** [comment]
> 
> 
> @FartingDaddy that url is to the old API methods so make sure you're updated to the 0.3.0 version, if so there might be some other messages logged. Emporia won't provide any support for this since we're not using a public API so they're free to change it up underneath us (what happened in this case)

When do you think you'll have it all working again?

**Comment by magico13** [comment]
> When do you think you'll have it all working again?

Hopefully tonight though the issues people are seeing aren't ones I'm having so debugging and fixing them might take a bit longer.

**Comment by skynet01** [comment]
Same as others here, i seem to be getting the same error as pleeplow20  

```
Error while setting up emporia_vue platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 198, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/emporia_vue/sensor.py", line 103, in async_setup_entry
    CurrentVuePowerSensor(coordinator_1min, id) for idx, id in enumerate(coordinator_1min.data)
TypeError: 'NoneType' object is not iterable
```

**Comment by chrwei** [comment]
after updating I'm getting these 2 errors

```
Error fetching sensor data: Error communicating with Emporia API: argument of type 'NoneType' is not iterable

Error while setting up emporia_vue platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 198, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/emporia_vue/sensor.py", line 103, in async_setup_entry
    CurrentVuePowerSensor(coordinator_1min, id) for idx, id in enumerate(coordinator_1min.data)
TypeError: 'NoneType' object is not iterable
```

I even completely removed and reinstalled in hacs too.

**Comment by FartingDaddy** [comment]
> @FartingDaddy that url is to the old API methods so make sure you're updated to the 0.3.0 version, if so there might be some other messages logged. Emporia won't provide any support for this since we're not using a public API so they're free to change it up underneath us (what happened in this case)

Hi again,

Now after another re-install with all the same problems:

Logger: homeassistant.components.sensor
Source: custom_components/emporia_vue/sensor.py:103
Integration: Sensor (documentation, issues)
First occurred: 8:54:03 PM (1 occurrences)
Last logged: 8:54:03 PM

Error while setting up emporia_vue platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 198, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/emporia_vue/sensor.py", line 103, in async_setup_entry
    CurrentVuePowerSensor(coordinator_1min, id) for idx, id in enumerate(coordinator_1min.data)
TypeError: 'NoneType' object is not iterable

**Comment by magico13** [comment]
For everyone experiencing issues can you please do the following:
1. Remove the existing integration in the Integrations view
2. Go into HACS and find the Emporia Vue integration
3. From the 3 dots dropdown select Update Information and then Reinstall
4. Select "master" as the version and install it (might need to enable beta versions)
5. Restart Home Assistant
6. Add the integration again, selecting the default sensors (1 minute, 1 day, 1 month)
7. Go into the `/config/logs` endpoint, load full log, copy and paste anything you see after the first mention of `emporia` (if there is anything) into a comment on here.

I added some more logging and tried to add some more checks for invalid values but still can't recreate the issues here. If you're comfortable [enabling information level logging](https://www.home-assistant.io/integrations/logger/) there are more messages that might help me diagnose what's happening.

**Comment by DaDre** [comment]
Oh sure, of course, now that you post that it all instantly works... :) following the step by step above brought all my sensors back. I'm baffled. Thank you so much @magico13! Really enjoying the fruits of your labor. You got a tip jar?

**Comment by pixeron** [comment]
I followed the steps and it is back and running now. The only difference now was that instead v3 I choose "master". from the list. Thank You for great work!

**Comment by FartingDaddy** [comment]
Hi, good morning everyone,

Yes ! it works, partially. I am missing the 1hr, 1 min, 1 sec sensor readings. But we are moving ahead - thank you MUCH, Magico13. Below my first log that mentions emporia. No additional ones at the moment.

Logger: custom_components.emporia_vue.sensor
Source: custom_components/emporia_vue/sensor.py:68
Integration: Emporia Vue (documentation)
First occurred: 6:59:10 AM (5 occurrences)
Last logged: 7:02:14 AM

No channels found during update

**Comment by alancarrillo** [comment]
Its working again. I followed the steps.
Thank you for your work @magico13 
![20210211_105935](https://user-images.githubusercontent.com/14023088/107670730-a66cc480-6c58-11eb-80b4-096725a1b84a.jpg)

**Comment by BillyFKidney** [comment]
Updating HACS then the Emporia Due integration fixed it for me as well.
<img width="468" alt="image" src="https://user-images.githubusercontent.com/65253277/107678235-00b55780-6c50-11eb-9ea4-d50b893dd752.png">

**Comment by chrwei** [comment]
all fixed for me too.  latest change seemed to do the trick.

**Comment by chanders** [comment]
All fixed when using "master" as recommended above *thumbsup*

**Comment by skynet01** [comment]
Is the "seconds" sensor work for anyone? When i try to add just the second sensor i get an unknown error in login dialogue

**Comment by chrwei** [comment]
seconds is working fine for me

**Comment by imac13kathleen** [comment]
Seconds works for me as well. Thank you Magico13!  Amazing work.  

With the addition of SECONDS, I can now use HA for some pretty great energy management.  When my house is running on Generator or Solar only, and my total home power is limited, I can monitor total usage, and if a device for which I don't have HA control of comes on, I can power off devices for which I do have control, very quickly.  I'd say it takes less than 1.5 seconds all in for a heater to power off if I flick the oven on.  Which, was a full manual process for me before the SECONDS integration.  Well done!!!

**Comment by chrwei** [comment]
and now seconds is no longer working, says they are all orphaned, I'm not see any related errors in the logs.  Only thing i have is an occasional 500 error, but it's always with a scale=1MIN url.

howeever, restarting homeassisant brought them back

**Comment by skynet01** [comment]
I can confirm that I also have the sensors crash sometimes with 500 error and restarting HA fixes it. I think it's related to the ticket here: #13 as i get

```
Error fetching sensor1s data: Error communicating with Emporia API: 500 Server Error: Internal Server Error for url: https://api.emporiaenergy.com/AppAPI?apiMethod=getDevicesUsage&deviceGids=15928&instant=2021-02-22T23:00:46.004882Z&scale=1S&energyUnit=KilowattHours
```
and
```
First occurred: February 22, 2021, 2:41:36 PM (3141 occurrences)
Last logged: February 22, 2021, 4:00:32 PM

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 124, in _handle_refresh_interval
    await self.async_refresh()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 198, in async_refresh
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 258, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 296, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 320, in _async_write_ha_state
    sstate = self.state
  File "/config/custom_components/emporia_vue/sensor.py", line 194, in state
    usage = self.coordinator.data[self._id]["usage"]
KeyError: '15928-1,2,3-1S'
```

**Comment by magico13** [comment]
Doing some cleanup of old issues, looks like the initially reported problems in this one were resolved so I'm going to close this.
