### ISSUE TITLE
1 min reading keep disappearing

### ISSUE THREAD

**Issue by pudgenuts** [magico13/ha-emporia-vue#280]
in the last week or so I notice in HA seems to not be capturing the 1minute readings. These are available in the app. Hoping this isn't just me.

**Comment by DabblerIOT** [comment]
Working good here.  What version of ha, integration and pyemvue?

Anything in logs?

Im running my fork but its very close to main branch.  Have not updated to 6.1 release of ha.

**Comment by BenJewell** [comment]
The integration has also done this with me occasionally, maybe a couple times a month. Restarting home assistant brings it back.

**Comment by DabblerIOT** [comment]
Please upgrade to latest version of ha integration.   Many retries were added to the fetches from the emporia api (it returns 0 data or missing data often).   If there is a prolonged api outage you could still see this.   If it becomes a persistent issue please reopen and include some charts / data of missing data, type of device, and logs, versions of everything.
