### ISSUE TITLE
Emporia Vue 3

### ISSUE THREAD

**Issue by dfxinc** [magico13/ha-emporia-vue#287]
Does this work with the new Vue 3? and does it support Nesting of several units in a sub panel?

**Comment by magico13** [comment]
Yes and yes. I've got a Vue 3 that's working fine and I've also got a 1 nested under a 2 and that reports correctly.

This basically just calls the same API that the home page of the app uses, so the data that shows up in Home Assistant should look like the data from the app.

**Comment by dfxinc** [comment]
Excellent news, thanks very much.
