### ISSUE TITLE
Got told to open a ticket by the plugin.

### ISSUE THREAD

**Issue by PaleFlyer** [magico13/ha-emporia-vue#288]
Logger: homeassistant.util.loop
Source: util/loop.py:84
First occurred: 10:24:39 AM (1 occurrences)
Last logged: 10:24:39 AM

Detected blocking call to open inside the event loop by custom integration 'emporia_vue' at custom_components/emporia_vue/__init__.py, line 564: tz_info = dateutil.tz.gettz(tz_string) (offender: /usr/local/lib/python3.12/site-packages/dateutil/tz/tz.py, line 464: fileobj = open(fileobj, 'rb')), please create a bug report at https://github.com/magico13/ha-emporia-vue/issues Traceback (most recent call last): File "<frozen runpy>", line 198, in _run_module_as_main File "<frozen runpy>", line 88, in _run_code File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module> sys.exit(main()) File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main exit_code = runner.run(runtime_conf) File "/usr/src/homeassistant/homeassistant/runner.py", line 190, in run return loop.run_until_complete(setup_and_run_hass(runtime_config)) File "/usr/local/lib/python3.12/asyncio/base_events.py", line 672, in run_until_complete self.run_forever() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 639, in run_forever self._run_once() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1988, in _run_once handle._run() File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run self._context.run(self._callback, *self._args) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 742, in async_setup_locked await self.async_setup(hass, integration=integration) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup result = await component.async_setup_entry(hass, self) File "/config/custom_components/emporia_vue/__init__.py", line 185, in async_setup_entry await coordinator_1min.async_config_entry_first_refresh() File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 277, in async_config_entry_first_refresh await self._async_refresh( File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 312, in _async_refresh self.data = await self._async_update_data() File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 268, in _async_update_data return await self.update_method() File "/config/custom_components/emporia_vue/__init__.py", line 126, in async_update_data_1min data = await update_sensors(vue, [Scale.MINUTE.value]) File "/config/custom_components/emporia_vue/__init__.py", line 373, in update_sensors await parse_flattened_usage_data( File "/config/custom_components/emporia_vue/__init__.py", line 420, in parse_flattened_usage_data local_time = change_time_to_local(data_time, info.time_zone) File "/config/custom_components/emporia_vue/__init__.py", line 564, in change_time_to_local tz_info = dateutil.tz.gettz(tz_string)

**Comment by magico13** [comment]
Thanks! Already tracked under #288
