### ISSUE TITLE
Bi-Directional support

### ISSUE THREAD

**Issue by wildcard5** [magico13/ha-emporia-vue#290]
I have just noticed that the 'vue' now supports Bi-Directional monitoring on all circuits (software app update and a firmware update req) but monitoring in Home Assistant only works one way ( I have a battery system and in the app is shows import and export).
This really (for me) isn't an issue but just wondered if this could maybe be incorporated into a future update although I'm still running old code version (0.8) so may already be incorporated (I have never updated as it been flawless for me, I just have to reload on a HA restart)

Thanks.

**Comment by magico13** [comment]
I've started on the backend work required to detect that a circuit has been set to bidirectional and will hopefully get that change into the integration soon.

**Comment by Larry0ua** [comment]
Hi! Any chances to get this change to HACS release soon?

**Comment by Markyt77** [comment]
Is this still going to happen? Being able to see bi-directional flow would be super useful.
