### ISSUE TITLE
Can’t install repository 

### ISSUE THREAD

**Issue by adamtar** [magico13/ha-emporia-vue#292]
Is anyone having this issue in hacks? 
![IMG_2915](https://github.com/user-attachments/assets/9410396c-a060-4926-ac46-8d74211f37ba)

**Comment by magico13** [comment]
You are not in HACS in that screen. HACS doesn't have addons. Make sure you've installed HACS (see https://hacs.xyz/docs/setup/download/) and when you load HACS then choose Integrations. From there you'll add the repository URL as a custom integration and download it, and then afterwards you can configure the integration in the normal Integrations menu in Home Assistant.

**Comment by adamtar** [comment]
Thank you I tried doing it from mobile. Thats was the problem. Thanks for all of your hard work!
