### ISSUE TITLE
1D Sensors Missing

### ISSUE THREAD

**Issue by mbhforum** [magico13/ha-emporia-vue#293]
I just added my third Vue-2 to my home for an outdoor panel which powers my AC Compressors and Pool Equipment.  I got the devices added to Emporia fine, labeled, them, etc.  I then attempted to reload the Emporia-HA integration.  It imported each of my circuits, but only did so for MON and MIN, not 1D. Is this because a full day hasn't passed yet?

Another issue is, I have a bunch of oprhaned devices and I am not sure why they are appearing. I didn't have this issue with the first two VUE-2 systems I installed.

![image](https://github.com/user-attachments/assets/a3220754-50dd-49ca-a5ee-850a4b63e78a)

![image](https://github.com/user-attachments/assets/5cca1b5a-2000-4a91-893c-d0529c5a004b)

**Comment by magico13** [comment]
Could have been an issue during startup. Make sure they show up in the Emporia app, then try reloading the integration.

**Comment by mbhforum** [comment]
Thanks.    The Day shows some data in Emporia. I have tried reloading the integration but it doesn't create the 1D sensors.

![image](https://github.com/user-attachments/assets/f40ced9b-52c9-4a8c-bb7a-1908c693f5e1)

**Comment by mbhforum** [comment]
So they finally appeared.  Must have been a timing issue.  I still don't understand why I have all of those orphaned devices named "Outdoor Electrical Panel".
