### ISSUE TITLE
login integration

### ISSUE THREAD

**Issue by DaveR2419** [magico13/ha-emporia-vue#304]
When trying to reauthentic in integration I get unexpected error.
This error originated from a custom integration.

Logger: custom_components.emporia_vue.config_flow
Source: custom_components/emporia_vue/config_flow.py:78
integration: Emporia Vue (documentation, issues)
First occurred: 6:37:59 PM (2 occurrences)
Last logged: 6:40:56 PM

Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/emporia_vue/config_flow.py", line 78, in async_step_user
    await self.async_set_unique_id(info["gid"])
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 2389, in async_set_unique_id
    raise data_entry_flow.AbortFlow("already_in_progress")
homeassistant.data_entry_flow.AbortFlow: Flow aborted: already_in_progress

**Comment by magico13** [comment]
"Already in progress" is odd to see. Two suggestions, first is to reboot and try again, second is to remove the integration and reinstall it.

**Comment by DaveR2419** [comment]
I will try and let you know.

**Comment by DaveR2419** [comment]
Reinstall did fix the issue, thanks.

**Comment by DaveR2419** [comment]
Thanks for the great work magico13
