### ISSUE TITLE
Seconds Not Showing up

### ISSUE THREAD

**Issue by pleeplow20** [magico13/ha-emporia-vue#31]
I Don't have seconds anymore I get this in the logs 

Logger: custom_components.emporia_vue.sensor
Source: custom_components/emporia_vue/sensor.py:151
Integration: Emporia Vue (documentation)
First occurred: 4:28:26 PM (3 occurrences)
Last logged: 4:30:32 PM

No data found for 1 second updater

**Comment by magico13** [comment]
Doing some cleanup of old issues. Seconds support was removed in 0.5.0 at Emporia's request. If you encounter any additional issues please open a new ticket.
