### ISSUE TITLE
Fetch "Balance minute average"

### ISSUE THREAD

**Issue by iku777** [magico13/ha-emporia-vue#312]
Hi,

I have just installed version 10.0.
I noticed that the "[Sensor] 1MIN" has been replaced by "Power minute average', which is working fine.
Would it be possible to also fetch that "minute average" for the Balance device?
Right now I have Energy this month, Energy today and Home Balance 1MIN (from the previous version) with the last one showing as unavailable. All other devices don't have this 1MIN version but have the "minute average" sensor.
![Screenshot 2024-09-21 085545](https://github.com/user-attachments/assets/38f11e0a-5720-436c-acef-83ca72f2d6eb)
![Screenshot 2024-09-21 085602](https://github.com/user-attachments/assets/9e89c69e-26de-4312-b9d7-c4d4905a5303)

**Comment by magico13** [comment]
Odd, the balance should still populate. Might have been something not working properly during startup. Try reloading the integration from the integrations page, or rebooting, and that might populate it.

**Comment by iku777** [comment]
Hi. I have tried reloading the integration and the "balance minute average" did appear properly.
That is indeed odd as I have just rebooted post upgrade and it showed up with this glitch.
Anyhow, thanks for the quick reply:)
