### ISSUE TITLE
Incorrectly returning absolute usage values for merged bidirectional circuits

### ISSUE THREAD

**Issue by apetryk2** [magico13/ha-emporia-vue#331]
I have solar feeding into a sub-panel and emporia accurately measures usage on the circuit that feeds that sub-panel as negative when solar is generating and positive when it is not.  That subpanel is fed by a 240V breaker and has two emporia sensors on it that I've merged into one sensor in the app.

I tested pyEmvue and it correctly displays the sign of usage.

In the homeassistant version we check the type of the channel to see if it is bidirectional to determine whether or not to return the absolute value of the usage.

Unfortunately the circuit type for my subpanel is "Merged" because I use two sensors to measure the output.  Each of the underlying circuits has a type of "FiftyAmpBidirectional".

Because the type is "Merged" we fail the "bidirectional' test in the call to fix_usage_sign:

            fixed_usage = fix_usage_sign(
                channel_num, fixed_usage, "bidirectional" in info_channel.type.lower()
            )

**Comment by magico13** [comment]
Should be fixed in v0.10.1 but feel free to reopen if it's still causing issues.

**Comment by apetryk2** [comment]
Thanks Mike - I confirm that the v0.10.1 fixes this issue.

**Comment by gruebane01** [comment]
I'm afraid this fix introduced a new problem.  In my case, the solar feed is grid-tied (i.e. upstream from the breakers hooked onto the mains).  I have clamps on the red and black lines and a merged circuit in Emporia for measuring the generation.  Once I installed this update, my solar input is now reading negative.

![image](https://github.com/user-attachments/assets/98827f6c-a2d3-4863-8be6-07598fa10845)

**Comment by saydo17** [comment]
> Once I installed this update, my solar input is now reading negative.

Same issue for me

**Comment by apetryk2** [comment]
What does it show in the emporia app?  In my app my solar circuit is a negative value (since it is generating) and the other circuits that are consuming power are positive values.  Before the fix the homeassistant values were inconsistent with the app but now they are consistent.

**Comment by gruebane01** [comment]
The difference is that, in my case, solar is upstream from the circuit panel, tied onto the mains.  In your case, you are downstream.  Both are supported configurations with Emporia (setups for each are in the install documentation) and their app/platform can understand when you configure it all.

My view in Emporia:
![Screenshot_20241231-122329](https://github.com/user-attachments/assets/41a27ddc-8957-4591-a05f-8282efafe8a2)

**Comment by apetryk2** [comment]
When you click on the "solar" which is green in your screenshot what does it show as the average rate in the top right of the chart?  In mine it shows the average rate as a negative value in the app which is now accurately reflected in HA (before it was negative in the app but positive in HA because of the absolute value conversion).

**Comment by gruebane01** [comment]
Negative, just like yours.

![Screenshot_20241231-131908](https://github.com/user-attachments/assets/11e5dd42-ef9a-417f-8ec3-5db4f38c32d2)

**Comment by pmyers** [comment]
Just weighing in to say that I am experiencing the same issue as @gruebane01 and others. Upgrading to 0.10.1 in HACS caused my HA values to be negative for solar, but they display just fine in the Emporia app.
