### ISSUE TITLE
Future Home Assistant (2021.6) Requires a version key in the manifest file

### ISSUE THREAD

**Issue by focher** [magico13/ha-emporia-vue#37]
The Home Assistant log is now displaying the following:

```[homeassistant.loader] No 'version' key in the manifest file for custom integration 'emporia_vue'. As of Home Assistant 2021.6, this integration will no longer be loaded. Please report this to the maintainer of 'emporia_vue'```

**Comment by magico13** [comment]
Thanks for the heads up. There's already a merged PR to add the version file, there's just not a release with it yet, so it will get addressed in the next release. I'll leave this issue open until the release is made (no estimate yet, still debating which features to include)

**Comment by magico13** [comment]
Version key added in 0.4.0
