### ISSUE TITLE
Add Sensors for Daily/Monthly/Yearly/Lifetime Usage

### ISSUE THREAD

**Issue by magico13** [magico13/ha-emporia-vue#4]
I'm not sure if we need all of these or if there's a way to set that up in Home Assistant (daily is basically the sum of the last 24 hours of readings, monthly is the sum of the dailies, etc). Monthly seems the most useful since that's generally close to the amount billed.

These readings all theoretically correspond to a particular device/channel so it might be worthwhile to try to group the separate sensors into actual "devices" in home assistant.

There are two API calls that are relevant, [/usage/total](https://github.com/magico13/PyEmVue/blob/master/api_docs.md#get-total-usage-for-a-time-frame) which gives month-to-date or all-to-date for a device/channel and [/usage/devices](https://github.com/magico13/PyEmVue/blob/master/api_docs.md#get-recent-total-device-usage) which is a single call that gives data for every device/channel over the specified range. The second call might not work well for month-to-date style readings which is what would be useful for estimating billing, I'll have to do some additional testing.

**Comment by skynet01** [comment]
I just set it all up using utility-meter integration, wouldn't that produce the same result? We can also add this data as sensor attributes so that we don't have to create additional sensors.. since it will be a lot of extra sensors if you are monitoring 16 channels  :)

**Comment by magico13** [comment]
It should end up with basically the same result. There might be some value in pulling the data straight from the API but I might just recommend people use that integration (link [here](https://www.home-assistant.io/integrations/utility_meter/))

**Comment by magico13** [comment]
Daily/Monthly added in v0.2.0. I may add others later if there is demand.
