### ISSUE TITLE
Cost instead of kwh/watts

### ISSUE THREAD

**Issue by KJThaDon** [magico13/ha-emporia-vue#48]
How can I enable costs as a unit of measurement?

**Comment by magico13** [comment]
Currently there isn't a way to do that directly within the integration. There might be a way to use another integration to create sensors that take the existing kwh data and multiply by your rate. I can look into adding support for it at some point directly within this integration.

**Comment by KJThaDon** [comment]
> Currently there isn't a way to do that directly within the integration. There might be a way to use another integration to create sensors that take the existing kwh data and multiply by your rate. I can look into adding support for it at some point directly within this integration.

Awesome, appreciate the integration! Just got my setup done and this running and it's fabulous so far. Wanted to add costs measurement for the wife. The watts and kwh are gibberish to them lol.

Looking forward to it if possible. Thank you

**Comment by haddood** [comment]
cost might be very complicated depending on where you are ... if it is simple flat rate, you can use template sensors to convert the KWh to money ... example below, I created input number called kwh_price so I can input the rate from GUI and not hard coded into the sensor. 

{{ (states.sensor.power_your_sensor_123_1mon.state|float) * (states.input_number.kwh_price.state|float) }}

**Comment by magico13** [comment]
The new energy dashboard built into Home Assistant has the ability to add a cost sensor that I recommend using instead of something I develop specifically for this. With that, I'm going to close this request.

**Comment by Trebacz** [comment]
@magico13 Can you give a little guidance on the cost sensor? https://www.home-assistant.io/integrations/utility_meter is that what your thinking? PS Thanks for the great integration and getting the energy integration working so well and quick.

**Comment by magico13** [comment]
When you set up the energy dashboard it will create a cost sensor for you. In my case that's easy because my electricity is a fixed rate but if your rate changes then you'll have to do what's mentioned in your link to set up different tariffs so it calculates correctly. I'll be honest, I haven't gone through that myself because my costs are fixed and in the fixed case you just enter the price per kWh when setting up the energy dashboard.
