### ISSUE TITLE
Entering login information?

### ISSUE THREAD

**Issue by ifuchs** [magico13/ha-emporia-vue#50]
I have Emporia Vue installed , or at least it shows up under HACS->Integrations. How do I now enter my Emporia credentials? The info page says:
```
After installation, enable the integration in the Home Assistant integration configuration page, then enter the email and password used for the Emporia app.
``` 
but I'm not seeing that.

**Comment by magico13** [comment]
If you haven't already, restart your Home Assistant instance. Then go to the regular Integrations page, search for Emporia, and it should show up. If not then it's usually due to your browser caching data, you can try a Ctrl-shift-r or Ctrl-F5 to force it to reload and it'll hopefully show up then.

**Comment by ifuchs** [comment]
Bingo! I didn't realize I needed to add it (again) as a regular Integration. I have now logged in and can see my sensor data.
Thanks!

**Comment by ifuchs** [comment]
I see the minute and month values, is the second value available as it is in the Vue app?

**Comment by magico13** [comment]
Not anymore. Emporia asked the community to keep the API usage down to about 2k requests a day and the one second sensor is just way too frequent to be useable with that constraint. Until we get local access we won't get 1 second data in Home Assistant, but the VueGraf application that someone wrote can pull that data into an InfluxDB instance for historical reporting.

**Comment by ifuchs** [comment]
I figured that was the reason. We definitely need local access to the real-time data!
