### ISSUE TITLE
Minute interval not showing up

### ISSUE THREAD

**Issue by ifuchs** [magico13/ha-emporia-vue#51]
Why do some of my devices show the minute interval and others only the Day and Month?

**Comment by magico13** [comment]
They should all show up but occasionally the data it gets back when first loading is incomplete. If you go into the Integrations and select the three dots next to the Emporia integration, then select the reload option, it should run through all of the initialization again and they should hopefully all show up then.

**Comment by chanders** [comment]
I had the same issue and followed @magico13 's suggestion and all is well. 

@ifuchs I believe he meant the "reinstall" option and not "reload". That's what I did.

**Comment by ifuchs** [comment]
Thanks, that worked!

**Comment by magico13** [comment]
Reload from the HA Integrations menu should be sufficient, but a reinstall should also work since it'll go through the setup again. Restarting Home Assistant also would likely work.
