### ISSUE TITLE
Support for HA Energy Dashboard

### ISSUE THREAD

**Issue by magico13** [magico13/ha-emporia-vue#53]
There are a few changes needed to support the new statistics and energy dashboard. See the links below

https://developers.home-assistant.io/docs/core/entity/sensor/#long-term-statistics
https://www.home-assistant.io/blog/2021/08/04/home-energy-management/
https://www.home-assistant.io/docs/energy/

I'm not yet sure if the energy dashboard will run off of the minute sensor (ideally, since it updates the most frequently) or the daily sensor.  The Riemann Sum integration might be able to take the minute data and build a higher resolution daily sensor if needed, or we could look into trying to build something similar inside this integration.

**Comment by john-k-mcdowell** [comment]
Is there a path forward for moving this integration into the core.  Given this new push on energy monitoring, Emporia is a great solution for those who don't have electric meters with digital output and a better solution than trying to build an ESPHome solution from scratch.  I know Emporia has been open to discussions with you on the Python library so I think we can look at them as a good long term solution as well.  I wish we could a local integration rather than a cloud integration, but for now the cloud works very well.

**Comment by magico13** [comment]
> Is there a path forward for moving this integration into the core?

Home Assistant does document the requirements for submitting an integration into the core and it would take a good chunk of work to get this in line with them. Since this has really just been a side project for me I haven't pursued that too strongly up to this point. I think a decent intermediate step is getting this added to the HACS default repository.

I would personally like to see an officially supported API (or local access) from Emporia before I'd feel comfortable with this being in the core since at the moment they have no obligation to maintain the current API as-is. They have made big changes to the API before and likely could again.

**Comment by john-k-mcdowell** [comment]
This makes sense.  I am curious if we can figure out how to use HA 2021.8 Energy Monitoring focus as a way of getting Emporia more engaged with the HA community/supported API.  I am willing to help however I can but I am not a skilled enough developer to help with getting the integration into the core.

**Comment by magico13** [comment]
I pushed up a change so now the 1D and 1M sensors show up as options in the energy dashboard but am still doing testing on it to see how well it works. So far nothing is actually showing up in the dashboard but there's the whole "could take two hours" thing. If that goes well then I'll likely have the official update out tomorrow.

I am also doing some testing with the built-in Riemann Sum integration off the 1min sensor. In case you want to try that out (no update to this integration required), here's what I'm testing with:

```yaml
sensor:
  - platform: integration
    source: sensor.power_home_123_1min
    name: integrated_energy_home
    unit_prefix: k
    unit_time: h
    method: right
    round: 2
```

**Comment by oziee** [comment]
I have tried and its been way over 2 hrs since I set it all up with the changed code 0.5.1 from here.. and nothing is showing still in the energy tab

I have added the power items to the recorder just in case it needed to record them too and still nothing

**Comment by DarwinData** [comment]
Thank you for this wonderful integration.  I too would like to see it work with the new Energy feature in HA. Thanks!

**Comment by magico13** [comment]
> I have tried and its been way over 2 hrs since I set it all up with the changed code 0.5.1 from here.. and nothing is showing still in the energy tab

I did a bunch of work on this last night (0.5.2) and it should be working better with the energy dashboard. I'm still doing testing though. You have to use the day sensor but I'm integrating the minute data into it now so it's much smoother. I'm also requesting the day data once every fifteen minutes but I might reduce that to every 30 minutes before release.

This is what it looks like for me today. I don't have solar that I can test with unfortunately.
![Screenshot_20210806-094632](https://user-images.githubusercontent.com/5289685/128520513-eb84ab03-f7ff-4e94-b9f9-2dda0e6e3b08.png)

**Comment by chanders** [comment]
@magico13 this looks great. Cant wait to test it out. Thanks again for your great work.

**Comment by chanders** [comment]
> I have tried and its been way over 2 hrs since I set it all up with the changed code 0.5.1 from here.. and nothing is showing still in the energy tab
> 
> I have added the power items to the recorder just in case it needed to record them too and still nothing
> 
> I did notice that the energy items seem to want kWh units.. and any items that are W etc do not list
> 
> the power energy card works ok
> <img alt="Screen Shot 2021-08-06 at 4 26 29 pm" width="513" src="https://user-images.githubusercontent.com/1471841/128465967-b728af8a-29fd-4d70-8b6d-acfcd2e1aee0.png">

Wow, you mind sharing the basics of the Solar system you have setup?

**Comment by magico13** [comment]
Just released v0.6.0 with official support for this. Let me know your feedback and open an issue if you encounter any bugs. Thanks!

![image](https://user-images.githubusercontent.com/5289685/128584387-0ed93914-9863-4186-bd6a-98606757cb90.png)

**Comment by DarwinData** [comment]
![image](https://user-images.githubusercontent.com/46134687/128696863-e8ec5c46-12f5-4832-8f9d-5c41818e00e3.png)
![image](https://user-images.githubusercontent.com/46134687/128696975-33b03ba4-f188-4dbf-abab-58230ce362cd.png)

My graph is not populating. No error messages.  Entity attributes look ok.  
Any ideas?
thanks

**Comment by DarwinData** [comment]
Just to follow up I found the problem.
I had excluded all entities in the recorder and then added only those entities that I wanted to track, in order to keep the database size down.  
Once I added the Vue entities to the recorder the graph came alive.
thanks for your excellent work on this component!

**Comment by Ragingfire105** [comment]
I see this has been closed so let me know if I should open a new issues instead,

You don't have solar so I can see how this got missed.  The values come is as negative for both Solar Clamps and 'Solar to Grid' readings.  I guess emporia does this for ease of calculation.  Unfortunately HA is expecting only positive values for all of the readings.  So the only graph that populates is energy from the grid.

**Comment by magico13** [comment]
@Ragingfire105 Could you open a new issue for that? I'll probably just have to flip the sensors to positive but unfortunately that'll mess up the history and any automations that expect them to be negative.

**Comment by oziee** [comment]
can this help. I have solar and this is the data

![IMG_6426](htt
[B8C44C-home-1SEC.csv](https://github.com/magico13/ha-emporia-vue/files/6964859/B8C44C-home-1SEC.csv)
ps://user-images.githubusercontent.com/1471841/128944359-63b2df0a-fc37-4cd4-811d-c01c2e527387.PNG)
![IMG_6425](https://user-images.githubusercontent.com/1471841/128944373-c94092a7-07b0-407a-91a0-8f8f69277772.PNG)
[B8C44C-home-1DAY.csv](https://github.com/magico13/ha-emporia-vue/files/6964856/B8C44C-home-1DAY.csv)
[B8C44C-home-1H.csv](https://github.com/magico13/ha-emporia-vue/files/6964857/B8C44C-home-1H.csv)
[B8C44C-home-1MIN.csv](https://github.com/magico13/ha-emporia-vue/files/6964858/B8C44C-home-1MIN.csv)

**Comment by oziee** [comment]
here are the supporting images from HA that show the current settings and what is measured and what is displayed

hope this can help

![IMG_6428](https://user-images.githubusercontent.com/1471841/128986970-1b066928-f24d-45d9-a171-007970d0ae0e.PNG)
![IMG_6430](https://user-images.githubusercontent.com/1471841/128987041-a214f109-b7af-410a-86aa-376fb8dc040b.PNG)
![IMG_6433](https://user-images.githubusercontent.com/1471841/128987126-232e5fcc-30f8-4cad-9aee-ff2c5f1ce26c.PNG)
![IMG_6432](https://user-images.githubusercontent.com/1471841/128987149-7e780c02-c849-4e96-8ad9-2dc6454b85cd.PNG)

**Comment by Kranzy** [comment]
@oziee sorry for this being off topic. I have just installed a Vue2 and have setup the integration. Did you need to do anything to get your circuit_1D sensors? Does it just take time for them to be created and appear in the integration?

**Comment by Ragingfire105** [comment]
> @oziee sorry for this being off topic. I have just installed a Vue2 and have setup the integration. Did you need to do anything to get your circuit_1D sensors? Does it just take time for them to be created and appear in the integration?

I have a vue2.  From the integration page I have a device for the unit itself, total usage, and then a device for each input/circuit.  Each circuit gets a 1min, 1d and 1mon.  When you added the integration did you accidently uncheck the one day sensor option?

![Screenshot_20220526-215442](https://user-images.githubusercontent.com/59106079/170619735-8efcba8d-ce24-415c-ad05-7fb010a2799c.png)
