### ISSUE TITLE
statistics?

### ISSUE THREAD

**Issue by Vansmak** [magico13/ha-emporia-vue#56]
https://developers.home-assistant.io/docs/core/entity/sensor#long-term-statistics

**Comment by magico13** [comment]
They should be working with the latest release. I've got a statistics chart for the 1 minute sensor on my dashboard showing min/max/avg per hour for several days.

![Screenshot_20210810-123701](https://user-images.githubusercontent.com/5289685/128898786-52e68c6f-710a-4ef7-a77b-9c4201455761.png)

**Comment by Vansmak** [comment]
ill let you know, restarting now.
