### ISSUE TITLE
Emporia site possibly down?

### ISSUE THREAD

**Issue by DarwinData** [magico13/ha-emporia-vue#62]
I have been receiving the following error for the last few hours.  Is the Emporia site down or has something changed?
I am using HASS OS and I am on the latest version of core at core-2021.8.7.  Same thing happened yesterday for a couple of hours and a restart fixed it.  Today restarts do not help.  My internet connection is good.
thanks

Exception while setting up Emporia Vue. Will retry. 400 Client Error: Bad Request for url: https://api.emporiaenergy.com/customers/xxxx/devices?detailed=true&hierarchy=true

**Comment by magico13** [comment]
Check HACS for an update, I just fixed this. There was a backing API change.

**Comment by DarwinData** [comment]
OK, I updated and I am now getting:

```
Unexpected error fetching sensor data: unsupported operand type(s) for +=: 'float' and 'NoneType'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 187, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 147, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/emporia_vue/__init__.py", line 146, in async_update_day_sensors
    last_day_data[day_id]["usage"] += data[
TypeError: unsupported operand type(s) for +=: 'float' and 'NoneType'
```

**Comment by stratfordwill** [comment]
I had the same errors as DarwinData upon updating and restarting HA. I then reloaded the integration and restarted HA. The error has not reappeared in the log and all data is populating now.

**Comment by magico13** [comment]
I think that could only happen if the data for a channel was missing. I should be able to fix that when I do some more work on this tonight. It was a bit of a rush job.

**Comment by akballow** [comment]
Thanks for the incredibly fast fix!

**Comment by skynet01** [comment]
Thanks for quick fix, i am getting this error though. Let me know if you would like my account info to test it out

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 368, in async_add_entities
    tasks = [
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 368, in <listcomp>
    tasks = [
  File "/config/custom_components/emporia_vue/sensor.py", line 41, in <genexpr>
    CurrentVuePowerSensor(coordinator_1hr, id)
  File "/config/custom_components/emporia_vue/sensor.py", line 73, in __init__
    raise RuntimeError(
RuntimeError: No channel found for device_gid 15928 and channel_num TotalUsage
```

**Comment by magico13** [comment]
Interesting, someone else mentioned TotalUsage not showing up when using the library directly. Another item for the list that I'll try to handle tonight

**Comment by magico13** [comment]
Everything mentioned in here should be fixed with 0.6.4, let me know if you still have any issues.

**Comment by Eightplant** [comment]
Update worked for me.  Took a minute or so for the 1D data to update.
Thanks!  I just got a Vue a couple of days ago.

**Comment by skynet01** [comment]
Everything works here again after your latest update. Thank youz! ❤️

**Comment by happydutch** [comment]
+1, thank you!

**Comment by tteck** [comment]
Just a FYI in the upcoming September release of HA state class changed
`STATE_CLASS_MEASUREMENT` changes to `STATE_CLASS_TOTAL_INCREASING`
in the sensor.py I've made the change in my sensor.py and is working (running dev branch)

**Comment by DarwinData** [comment]
Just updated to 0.6.4 and back in business.  Thanks for your great work on this!

**Comment by ifuchs** [comment]
I had same problems this morning so I reinstalled the Integration. Now I am getting:
`Retrying setup: Exception while setting up Emporia Vue. Will retry. 400 Client Error: Bad Request for url: https://api.emporiaenergy.com/customers/1234/devices?detailed=true&hierarchy=true `

**Comment by magico13** [comment]
> I had same problems this morning so I reinstalled the Integration.

That's the old url and was one of the things fixed. Make sure you're on 0.6.4 and that you restart home assistant

**Comment by ifuchs** [comment]
Sorry, my fault...I thought the reinstall would get the updated version. I updated and it works fine now. Thanks!

**Comment by magico13** [comment]
Alright, I think everything in here is addressed so I'm gonna close this. If you have any other problems please feel free to open a new issue!
