### ISSUE TITLE
After API Update, Toggling Switches not working

### ISSUE THREAD

**Issue by efficiencynerd** [magico13/ha-emporia-vue#63]
First of all, thanks for all the hard work, and for slacking off your day job to update within hours of the API change 😄 

I updated to 0.6.3 and things started working beautifully. The balance sensor works great.

However, I did notice that when I try to toggle one of my switches, HA gives an error which says:

400 Client Error: Bad Request for url: https://api.emporiaenergy.com/devices/outlet

I assume this is also just related to the API change.

**Comment by magico13** [comment]
Seeing it here too, will add that to the list of things to fix tonight, thanks!

**Comment by DaDre** [comment]
Thanks @magico13, your efforts are much appreciated!

**Comment by magico13** [comment]
Should be fixed now with 0.6.4!

**Comment by JP13090** [comment]
That did the trick!!  Thank you, sir!

While I will forever miss the 1s sensors, this is by far the most used entity in my lovelace and automations.  Thanks for your great work!

**Comment by DaDre** [comment]
Confirming, all is well here too.

**Comment by efficiencynerd** [comment]
Work for me as well, and thanks again for the super fast updates!
