### ISSUE TITLE
Last Reset value doesn't align with when 1D sensor resets causing sum statistic to not calculate

### ISSUE THREAD

**Issue by Zyell** [magico13/ha-emporia-vue#66]
When I updated for the breaking changes in the API, I found that my energy dashboard stopped showing everything except for solar production.  Upon investigating, I found that the last_reset value was no longer midnight, it was a timestamp taken from the device that constantly changed (and is more recent than the last hour).  Looking into my homeassistant db, I found that the sum for to mains and from mains no longer happened.  Other sensors were continuing to cumulatively sum successfully but not these (which I can't explain yet)...  When I altered the code to set the last_reset value back to midnight, the sums started working for these sensors.  I am running the latest version of homeassistant and from what I can tell, last_reset is going to go away as a requirement https://github.com/home-assistant/core/issues/54899#issuecomment-902492259 (thankfully!!), but at least for now, it seems required to get the consumption data to sum properly and appear in the energy dashboard.  I manually fixed my database and consumption data only appears if that cumulative sum in the statistics table works properly.  After waiting for additional calculations for the statistics, I see that the sum is working with the corrected last_reset value.

Would it be possible to add the last_reset back until this is fixed and no longer a dependency in homeassistant?

**Comment by Zyell** [comment]
So this is such a weird situation.  It is calculating the sum again with the last_reset value being prior to the last summary calculation, but the sum is wrong on most calculations.  I found this issue in home assistant: https://github.com/home-assistant/core/issues/54156  Even though it is pointing to a precision error, I think the issue is much worse/bigger than just that.  I'm thinking that this issue is more a home assistant problem.

**Comment by magico13** [comment]
Last Reset apparently is being removed anyway so in an upcoming release it won't even be set so that'll hopefully help prevent any of these sorts of weirdness.

**Comment by Zyell** [comment]
@magico13 Yes, I'm hoping it will correct the simply wrong sums that are being calculated.  Right now, I'm running a script to periodically fix these.  I really like the Energy dashboard a lot, just need it show correct statistics. :-)
