### ISSUE TITLE
Login does not work

### ISSUE THREAD

**Issue by Jmoore4717** [magico13/ha-emporia-vue#77]
I am trying to setup the Emporia integration after installing it and when putting in my email and password all i get is "Unexpected Error". I know 100% i am putting in the right credentials. I verified this by logging out and back in to the Emporia app. Does anyone know what the problem could be?

**Comment by magico13** [comment]
Most likely #30 which I'm planning on fixing later today.

**Comment by Jmoore4717** [comment]
Yep, I used all lowercase and it worked. Thanks for the quick response
