### ISSUE TITLE
Energy Dashboard 2021.9.0, Emporia Vue fails with Unexpected state class, does not have the expected state class 'total_increasing'

### ISSUE THREAD

**Issue by alvinchen1** [magico13/ha-emporia-vue#80]
Everything was working splendidly in 2021.8.8, where 1 Day Entities were working in both the Grid Consumption and Individual Device fields.  But update to 2021.9.0 now cannot use entities because they lack the attribute 'total_increasing' 

https://developers.home-assistant.io/docs/core/entity/sensor/#available-state-classes

**Comment by magico13** [comment]
Try reinstalling the "master" version through HACS, it's got some changes that were made for 2021.9 but don't work with 2021.8 and might fix this problem.

**Comment by alvinchen1** [comment]
👍 Nice, I see that the state_class changed to total_increasing.  I think that might fix my issue.  I won't know until later today/tomorrow because I already have 5 hours in Energy Dashboard with the old state_class, and Energy Dashboard was summing all values (previous and current) at each interval, instead of setting the value at the interval.

![image](https://user-images.githubusercontent.com/26409535/131817644-91a83d81-cbff-402a-b6da-b0a4aa463b85.png)

I certainly have not used 27 kWh during the 5 hours I've been asleep.  Emporia say 4.3 today, Energy Dashboard says 23.    I guess I will know in the next few hours if it is acting like it should, and will report back tomorrow if my dashboarrd is completely corrected.

Thanks again for your work.

**Comment by Grey-Lancaster** [comment]
I had the same error and reloading MASTER fixed it.  As well I had 2 entries for cost that said unknown.  Now they have readings again.
Thanks again,
Grey

**Comment by jbmk2** [comment]
![emporia HA](https://user-images.githubusercontent.com/78327006/131999834-20478a87-b293-4cbd-865d-d28d07bb3a4d.PNG)

Even after reinstaled, still with this problems.
Can you help?
Regards

**Comment by Grey-Lancaster** [comment]
What did you reinstall?
In HACS go to the integration>3 dots on right>reinstall> from the dropdown select Master

![image](https://user-images.githubusercontent.com/20055899/132002082-fe1a64d7-d1ca-49f9-815c-d5dc64288c54.png)

**Comment by magico13** [comment]
I'm going to try to get an update out today that's got the current master changes and flip the solar production to positive, which should at least clear those errors.

**Comment by jbmk2** [comment]
OK, master installed, now only missing the solar production to positive.
Thanks :-)

**Comment by skynet01** [comment]
The master works for me now. Isn't Mains to Grid sensor is the solar production value? And that's already positive for me. Btw thank you for adding Balance sensor :)

**Comment by magico13** [comment]
> Isn't Mains to Grid sensor is the solar production value

If you have a clamp on the wire coming from your inverter to your breaker box you can measure what's coming from the inverter directly. Because your house will use some of the power that number should be bigger than the MainsToGrid value. An example, if you have 1kw of solar coming in and 1kw of power used by your house, the MainsToGrid will be 0 and MainsFromGrid will also be 0.

As for the balance sensor, it started coming back in the new API calls so it actually got automatically added without me doing any extra work, so I can't claim any real credit for that, haha.

**Comment by alvinchen1** [comment]
Seems to be resolved.  Closing.
